#!/bin/bash



if [[ "$(uname)" == "Darwin" ]]; then # bash linux cannot deal with this no space ! check this 
    OS=Darwin;
    SUFFIX=osx
    CLOUD_DIR="/Users/tmkhoyan/surfdrive/"
    BASE_DIR="/Users/tmkhoyan/Desktop/data_wt/"
else
	OS=linux
    SUFFIX=linux
    CLOUD_DIR="/media/tmkhoyan/surfdrive/"
    BASE_DIR="/home/tmkhoyan/Desktop/data_wt/"
fi
echo "OS=$OS"


OPT_IMG_TYPE=tif
OPT_IMG_TYPE=jpg
OPT_COND=R1



OPT_CAM="CAM TE" # current
OPT_CAM_TE="CAM TE" # current
OPT_CAM_LE="CAM LE" # current

OPT_FILE_OUT_DIR="input"


OPT_IMAGEPATH_DIR="d2_c2_f5_g10_30/frames" 			     	# R1.  --> use this for jpeg
# OPT_IMAGEPATH_DIR="d2_c2_f5_g5_30/frames" 			     	# R2
# OPT_IMAGEPATH_DIR:="d3_c2_sweep_g10_30_corr/frames" 	     	# R3
OPT_IMAGEPATH_DIR="d2_c2_f5_g10_30/frames_jpg" 			     # R1.  --> use this for jpeg
# # OPT_IMAGEPATH_DIR="d2_c2_f5_g5_30/frames_jpg" 			     # R2
# OPT_IMAGEPATH_DIR="d3_c2_sweep_g10_30_corr/frames_jpg" 	     # R3

OPT_IMAGEPATH=${BASE_DIR}${OPT_IMAGEPATH_DIR}

OPT_FILE_OUT_LE=${OPT_FILE_OUT_DIR}/input_le_${OPT_IMG_TYPE}_${OPT_COND}_${SUFFIX}.txt
OPT_FILE_OUT_TE=${OPT_FILE_OUT_DIR}/input_te_${OPT_IMG_TYPE}_${OPT_COND}_${SUFFIX}.txt


[[ -d "$OPT_FILE_OUT_DIR" ]] || mkdir -p "$OPT_FILE_OUT_DIR" # create if doesnt exist

ls "$OPT_IMAGEPATH" | sort -n -t_ -k2 | grep ."$OPT_IMG_TYPE" | grep -i "$OPT_CAM_LE" | awk '{print}' | awk -v path="$OPT_IMAGEPATH" '{print path "/" $0}'  > "$OPT_FILE_OUT_LE"
ls "$OPT_IMAGEPATH" | sort -n -t_ -k2 | grep ."$OPT_IMG_TYPE" | grep -i "$OPT_CAM_TE" | awk -v path="$OPT_IMAGEPATH" '{print path"/" $0}'  > "$OPT_FILE_OUT_TE"

echo " generated image file: $OPT_FILE_OUT_LE"
echo " generated image file: $OPT_FILE_OUT_TE"